/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.jdbc.tutorial.form;

import com.jdbc.tutorial.dao.PersonDAO;
import com.jdbc.tutorial.entity.Person;
import com.jdbc.tutorial.model.PersonTableModel;
import java.util.Arrays;
import java.util.List;
import javax.swing.table.TableModel;
import org.springframework.context.support.ClassPathXmlApplicationContext;

/**
 *
 * @author asiro
 */
public class formPerson extends javax.swing.JFrame {

    private final List<Person> lModel=null;
    private int NSR = 0; //NumberSelectedRow
    private PersonDAO personDAO;
    private final ClassPathXmlApplicationContext context = new ClassPathXmlApplicationContext("spring.xml");

    /**
     * Creates new form formPerson
     */
    public formPerson() {
        personDAO = context.getBean(PersonDAO.class);
        //lModel = personDAO.listPerson();
        initComponents();
      //  context.close();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        letterPanel = new javax.swing.JPanel();
        emailButton = new javax.swing.JButton();
        letterButton = new javax.swing.JButton();
        recipientButton = new javax.swing.JButton();
        senderButton = new javax.swing.JButton();
        telButton = new javax.swing.JButton();
        workerButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel( new PersonTableModel(personDAO.listPerson()));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("Имя");

        jLabel2.setText("Страна");

        jButton1.setText("Добавить");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Редактировать");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Удалить");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        letterPanel.setLayout(new java.awt.GridLayout(3, 2));

        emailButton.setText("Email");
        emailButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailButtonActionPerformed(evt);
            }
        });
        letterPanel.add(emailButton);

        letterButton.setText("Letter");
        letterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letterButtonActionPerformed(evt);
            }
        });
        letterPanel.add(letterButton);

        recipientButton.setText("Recipient");
        recipientButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recipientButtonActionPerformed(evt);
            }
        });
        letterPanel.add(recipientButton);

        senderButton.setText("Sender");
        senderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                senderButtonActionPerformed(evt);
            }
        });
        letterPanel.add(senderButton);

        telButton.setText("Telefon");
        telButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telButtonActionPerformed(evt);
            }
        });
        letterPanel.add(telButton);

        workerButton.setText("Worker");
        workerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                workerButtonActionPerformed(evt);
            }
        });
        letterPanel.add(workerButton);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                            .addComponent(jTextField2)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, 0)
                        .addComponent(letterPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(10, 10, 10)
                .addComponent(letterPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        NSR = jTable1.getSelectedRow();
        TableModel model = jTable1.getModel();
        //String[] test = model.getValueAt(NSR, 1).toString().trim().split("\\s+");
        //System.out.println("!!!!!!!!!!!!"+Arrays.toString(test));
        jTextField1.setText(model.getValueAt(NSR, 1).toString());
        jTextField2.setText(model.getValueAt(NSR, 2).toString());
        //positionText.setText(model.getValueAt(NSR, 2).toString());
        //telText.setText(model.getValueAt(NSR, 3).toString());
        NSR = (int) model.getValueAt(NSR, 0);
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //personDAO = context.getBean(PersonDAO.class);
        personDAO.addPerson(new Person(jTextField1.getText(), jTextField2.getText()));
      //  context.close();
        jTable1.setModel(new PersonTableModel(personDAO.listPerson()));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Person p = new Person();
        p.setId(NSR);
        p.setName(jTextField1.getText());
        p.setCountry(jTextField2.getText());
        personDAO.updatePerson(p);
       // context.close();
        jTable1.setModel(new PersonTableModel(personDAO.listPerson()));
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        personDAO.removePerson(NSR);
        jTable1.setModel(new PersonTableModel(personDAO.listPerson()));
    }//GEN-LAST:event_jButton3ActionPerformed

    private void emailButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailButtonActionPerformed
        // TODO add your handling code here:
        FormEmail emailForm = new FormEmail();
        emailForm.setVisible(true);
        
    }//GEN-LAST:event_emailButtonActionPerformed

    private void letterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letterButtonActionPerformed
        // TODO add your handling code here:
        FormLetter letterForm = new FormLetter();
        letterForm.setVisible(true);
    }//GEN-LAST:event_letterButtonActionPerformed

    private void recipientButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recipientButtonActionPerformed
        // TODO add your handling code here:
        FormRecipient recipientForm = new FormRecipient();
        recipientForm.setVisible(true);
    }//GEN-LAST:event_recipientButtonActionPerformed

    private void senderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_senderButtonActionPerformed
        // TODO add your handling code here:
        FormSender senderForm = new FormSender();
        senderForm.setVisible(true);
    }//GEN-LAST:event_senderButtonActionPerformed

    private void telButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telButtonActionPerformed
        // TODO add your handling code here:
        FormTel telForm = new FormTel();
        telForm.setVisible(true);
    }//GEN-LAST:event_telButtonActionPerformed

    private void workerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_workerButtonActionPerformed
        // TODO add your handling code here:
        FormWorker workerForm = new FormWorker();
        workerForm.setVisible(true);
    }//GEN-LAST:event_workerButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formPerson.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formPerson.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formPerson.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formPerson.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formPerson().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton emailButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JButton letterButton;
    private javax.swing.JPanel letterPanel;
    private javax.swing.JButton recipientButton;
    private javax.swing.JButton senderButton;
    private javax.swing.JButton telButton;
    private javax.swing.JButton workerButton;
    // End of variables declaration//GEN-END:variables
}
