/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.jdbc.tutorial.form;

import com.jdbc.tutorial.entity.Worker;
import com.jdbc.tutorial.dao.WorkerDAO;
import com.jdbc.tutorial.model.WorkerTableModel;

import javax.swing.table.TableModel;

import org.springframework.context.support.ClassPathXmlApplicationContext;
/**
 *
 * @author asiro
 */
public class FormWorker extends javax.swing.JFrame {

    /**
     * Creates new form FormWorker
     */
    
    private final Worker worker = new Worker();
    private final ClassPathXmlApplicationContext context = new ClassPathXmlApplicationContext("springFB.xml");
    private final WorkerDAO workerDAO = context.getBean(WorkerDAO.class);
    private int NSR = 0;
    
    private void refresh(){
        WorkerTable.setModel(new WorkerTableModel(workerDAO.listWorker()));
    }
    
    private void addORupdate(String buf){
        worker.setPosition(positionText.getText());
        worker.setName(nameText.getText());
        worker.setSname(secondnameText.getText());
        worker.setPatronymic(patronymicText.getText());
        worker.setRecipient_id(new Integer(recipientText.getText()));
        switch (buf){
            case "add":
                workerDAO.addWorker(worker);
            case "update":
                worker.setId(NSR);
                workerDAO.updateWorker(worker);
        }
        this.refresh();
    }
    
    private String getValueTable(int nsr, int index){
        TableModel model = WorkerTable.getModel();
        return model.getValueAt(nsr, index).toString();
    }
    
    public FormWorker() {
        initComponents();
        this.refresh();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        WorkerTable = new javax.swing.JTable();
        dataPanel = new javax.swing.JPanel();
        positionLable = new javax.swing.JLabel();
        positionText = new javax.swing.JTextField();
        nameLabel = new javax.swing.JLabel();
        nameText = new javax.swing.JTextField();
        secondnameLabel = new javax.swing.JLabel();
        secondnameText = new javax.swing.JTextField();
        patronymicLabel = new javax.swing.JLabel();
        patronymicText = new javax.swing.JTextField();
        recipientLabel = new javax.swing.JLabel();
        recipientText = new javax.swing.JTextField();
        senderPanel = new javax.swing.JPanel();
        addButton = new javax.swing.JButton();
        editButton = new javax.swing.JButton();
        removeButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                нет(evt);
            }
        });

        WorkerTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        WorkerTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                WorkerTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(WorkerTable);

        dataPanel.setBackground(new java.awt.Color(255, 255, 255));
        dataPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        dataPanel.setLayout(new java.awt.GridLayout(5, 2));

        positionLable.setText("Position");
        dataPanel.add(positionLable);
        dataPanel.add(positionText);

        nameLabel.setText("Name");
        dataPanel.add(nameLabel);
        dataPanel.add(nameText);

        secondnameLabel.setText("SecondName");
        dataPanel.add(secondnameLabel);
        dataPanel.add(secondnameText);

        patronymicLabel.setText("Patronymic");
        dataPanel.add(patronymicLabel);
        dataPanel.add(patronymicText);

        recipientLabel.setText("Recipient");
        dataPanel.add(recipientLabel);
        dataPanel.add(recipientText);

        senderPanel.setBackground(new java.awt.Color(255, 255, 255));
        senderPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        senderPanel.setLayout(new java.awt.GridLayout(4, 1));

        addButton.setText("Add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });
        senderPanel.add(addButton);

        editButton.setText("Edit");
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });
        senderPanel.add(editButton);

        removeButton.setText("Remove");
        removeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeButtonActionPerformed(evt);
            }
        });
        senderPanel.add(removeButton);

        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        senderPanel.add(backButton);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(dataPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(senderPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(dataPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                    .addComponent(senderPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void WorkerTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_WorkerTableMouseClicked
        // TODO add your handling code here:
        NSR = WorkerTable.getSelectedRow();
        positionText.setText(this.getValueTable(NSR,1));
        nameText.setText(this.getValueTable(NSR, 2));
        secondnameText.setText(this.getValueTable(NSR, 3));
        patronymicText.setText(this.getValueTable(NSR, 4));
        recipientText.setText(this.getValueTable(NSR, 5));
        NSR = new Integer(this.getValueTable(NSR, 0));
    }//GEN-LAST:event_WorkerTableMouseClicked

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
        this.addORupdate("add");
    }//GEN-LAST:event_addButtonActionPerformed

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        // TODO add your handling code here:
        this.addORupdate("update");
    }//GEN-LAST:event_editButtonActionPerformed

    private void removeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeButtonActionPerformed
        // TODO add your handling code here:
        workerDAO.removeWorker(NSR);
        this.refresh();
    }//GEN-LAST:event_removeButtonActionPerformed

    private void нет(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_нет
        // TODO add your handling code here:
    }//GEN-LAST:event_нет

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        context.close();
        formPerson main = new formPerson();
        main.setVisible(true);
        this.hide();
    }//GEN-LAST:event_backButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormWorker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormWorker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormWorker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormWorker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormWorker().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable WorkerTable;
    private javax.swing.JButton addButton;
    private javax.swing.JButton backButton;
    private javax.swing.JPanel dataPanel;
    private javax.swing.JButton editButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameText;
    private javax.swing.JLabel patronymicLabel;
    private javax.swing.JTextField patronymicText;
    private javax.swing.JLabel positionLable;
    private javax.swing.JTextField positionText;
    private javax.swing.JLabel recipientLabel;
    private javax.swing.JTextField recipientText;
    private javax.swing.JButton removeButton;
    private javax.swing.JLabel secondnameLabel;
    private javax.swing.JTextField secondnameText;
    private javax.swing.JPanel senderPanel;
    // End of variables declaration//GEN-END:variables
}
