/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.jdbc.tutorial.form;

import com.jdbc.tutorial.entity.Recipient;
import com.jdbc.tutorial.dao.RecipientDAO;
import com.jdbc.tutorial.model.RecipientTableModel;

import javax.swing.table.TableModel;

import org.springframework.context.support.ClassPathXmlApplicationContext;
/**
 *
 * @author asiro
 */
public class FormRecipient extends javax.swing.JFrame {

    /**
     * Creates new form FormRecipient
     */
    
    private Recipient recipient = new Recipient();
    private final ClassPathXmlApplicationContext comtext = new ClassPathXmlApplicationContext("spring.xml");
    private final RecipientDAO recipientDAO = comtext.getBean(RecipientDAO.class);
    private RecipientTableModel recipientTableModel = new RecipientTableModel(recipientDAO.listRecipient());
    private int NSR = 0;
    
    private void refresh(){
        RecipientTable.setModel(recipientTableModel);
    }
    
    private void addORupdate(String buf){
        recipient.setName(nameText.getText());
        switch (buf){
            case "add":
                recipientDAO.addRecipient(recipient);
            case "update":
                recipientDAO.updateRecipient(recipient);
        }
        this.refresh();
    }
    
    public FormRecipient() {
        initComponents();
        this.refresh();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        RecipientTable = new javax.swing.JTable();
        nameLabel = new javax.swing.JLabel();
        nameText = new javax.swing.JTextField();
        addButtom = new javax.swing.JButton();
        editButton = new javax.swing.JButton();
        removeButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        RecipientTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        RecipientTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RecipientTableMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(RecipientTable, gridBagConstraints);

        nameLabel.setText("Name");
        nameLabel.setToolTipText("");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.ipadx = 67;
        getContentPane().add(nameLabel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.ipadx = 115;
        getContentPane().add(nameText, gridBagConstraints);

        addButtom.setText("Add");
        addButtom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtomActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        getContentPane().add(addButtom, gridBagConstraints);

        editButton.setText("Edit");
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        getContentPane().add(editButton, gridBagConstraints);

        removeButton.setText("Remove");
        removeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        getContentPane().add(removeButton, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RecipientTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RecipientTableMouseClicked
        // TODO add your handling code here:
        NSR = RecipientTable.getSelectedRow();
        TableModel model = RecipientTable.getModel();
        nameText.setText(model.getValueAt(NSR, ICONIFIED).toString());
        NSR = (int) model.getValueAt(NSR, 0);        
    }//GEN-LAST:event_RecipientTableMouseClicked

    private void addButtomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtomActionPerformed
        // TODO add your handling code here:
        this.addORupdate("add");
    }//GEN-LAST:event_addButtomActionPerformed

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        // TODO add your handling code here:
        this.addORupdate("update");
    }//GEN-LAST:event_editButtonActionPerformed

    private void removeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeButtonActionPerformed
        // TODO add your handling code here:
        recipientDAO.removeRecipient(NSR);
        this.refresh();
    }//GEN-LAST:event_removeButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormRecipient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormRecipient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormRecipient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormRecipient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormRecipient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable RecipientTable;
    private javax.swing.JButton addButtom;
    private javax.swing.JButton editButton;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameText;
    private javax.swing.JButton removeButton;
    // End of variables declaration//GEN-END:variables
}
