/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.jdbc.tutorial.form;

import com.jdbc.tutorial.entity.Sender;
import com.jdbc.tutorial.dao.SenderDAO;
import com.jdbc.tutorial.main.RunFormMain;
import com.jdbc.tutorial.model.SenderTableModel;

import javax.swing.table.TableModel;

import org.springframework.context.support.ClassPathXmlApplicationContext;
/**
 *
 * @author asiro
 */
public class FormSender extends javax.swing.JFrame {

    /**
     * Creates new form FormSender
     */
    private Sender sender = new Sender();
    private ClassPathXmlApplicationContext context = new ClassPathXmlApplicationContext("springFB.xml");
    private SenderDAO senderDAO = context.getBean(SenderDAO.class);
    private int NSR = 0;
    
    private void refresh(){
        SenderTable.setModel(new SenderTableModel(senderDAO.listSender()));
    }
    
    private void addORupadate(String buf){
        sender.setVed(vedText.getText().toString());
        sender.setName(nameText.getText().toString());
        sender.setAdres(adresText.getText().toString());
        sender.setRs(rsText.getText().toString());
        sender.setBank(bankText.getText().toString());
        sender.setKodbank(kodbankText.getText().toString());
        sender.setUnp(new Integer(unpText.getText()));
        switch (buf) {
            case "add":
                senderDAO.addSender(sender);
            case "update":
                sender.setId(NSR);
                senderDAO.updateSender(sender);
        }
        this.refresh();
    }
    
    private String getValueTable(int nsr, int index){
        TableModel model = SenderTable.getModel();
        return model.getValueAt(nsr, index).toString();
    }
    
    public FormSender() {
        initComponents();
        this.refresh();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        SenderTable = new javax.swing.JTable();
        dataPanel = new javax.swing.JPanel();
        vedLabel = new javax.swing.JLabel();
        vedText = new javax.swing.JTextField();
        nameLabel = new javax.swing.JLabel();
        nameText = new javax.swing.JTextField();
        adresLabel = new javax.swing.JLabel();
        adresText = new javax.swing.JTextField();
        rsLabel = new javax.swing.JLabel();
        rsText = new javax.swing.JTextField();
        bankLabel = new javax.swing.JLabel();
        bankText = new javax.swing.JTextField();
        kodbankLabel = new javax.swing.JLabel();
        kodbankText = new javax.swing.JTextField();
        unpLabel = new javax.swing.JLabel();
        unpText = new javax.swing.JTextField();
        senderPanel = new javax.swing.JPanel();
        addButton = new javax.swing.JButton();
        editButton = new javax.swing.JButton();
        removeButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SenderTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SenderTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(SenderTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 560, 170));

        dataPanel.setBackground(new java.awt.Color(255, 255, 255));
        dataPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        dataPanel.setLayout(new java.awt.GridLayout(7, 2));

        vedLabel.setText("Vedomstvo");
        dataPanel.add(vedLabel);
        dataPanel.add(vedText);

        nameLabel.setText("Name");
        dataPanel.add(nameLabel);
        dataPanel.add(nameText);

        adresLabel.setText("Adres");
        dataPanel.add(adresLabel);
        dataPanel.add(adresText);

        rsLabel.setText("RS");
        dataPanel.add(rsLabel);
        dataPanel.add(rsText);

        bankLabel.setText("Bank");
        dataPanel.add(bankLabel);
        dataPanel.add(bankText);

        kodbankLabel.setText("KodBank");
        dataPanel.add(kodbankLabel);
        dataPanel.add(kodbankText);

        unpLabel.setText("UNP");
        dataPanel.add(unpLabel);
        dataPanel.add(unpText);

        getContentPane().add(dataPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 280, 120));

        senderPanel.setBackground(new java.awt.Color(255, 255, 255));
        senderPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        senderPanel.setLayout(new java.awt.GridLayout(4, 1));

        addButton.setText("Add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });
        senderPanel.add(addButton);

        editButton.setText("Edit");
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });
        senderPanel.add(editButton);

        removeButton.setText("Remove");
        removeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeButtonActionPerformed(evt);
            }
        });
        senderPanel.add(removeButton);

        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        senderPanel.add(backButton);

        getContentPane().add(senderPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, 220, 120));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SenderTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SenderTableMouseClicked
        // TODO add your handling code here:
        NSR = SenderTable.getSelectedRow();
        vedText.setText(this.getValueTable(NSR, 1));
        nameText.setText(this.getValueTable(NSR, 2));
        adresText.setText(this.getValueTable(NSR, 3));
        rsText.setText(this.getValueTable(NSR, 4));
        bankText.setText(this.getValueTable(NSR, 5));
        kodbankText.setText(this.getValueTable(NSR, 6));
        unpText.setText(this.getValueTable(NSR, 7));
        NSR = new Integer(this.getValueTable(NSR, 0));
    }//GEN-LAST:event_SenderTableMouseClicked

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
        this.addORupadate("add");
    }//GEN-LAST:event_addButtonActionPerformed

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        // TODO add your handling code here:
        this.addORupadate("update");
    }//GEN-LAST:event_editButtonActionPerformed

    private void removeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeButtonActionPerformed
        // TODO add your handling code here:
        senderDAO.removeSender(NSR);
        this.refresh();
    }//GEN-LAST:event_removeButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        context.close();
        this.hide();
        RunFormMain.Run();
    }//GEN-LAST:event_backButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormSender.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormSender.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormSender.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormSender.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormSender().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable SenderTable;
    private javax.swing.JButton addButton;
    private javax.swing.JLabel adresLabel;
    private javax.swing.JTextField adresText;
    private javax.swing.JButton backButton;
    private javax.swing.JLabel bankLabel;
    private javax.swing.JTextField bankText;
    private javax.swing.JPanel dataPanel;
    private javax.swing.JButton editButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel kodbankLabel;
    private javax.swing.JTextField kodbankText;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameText;
    private javax.swing.JButton removeButton;
    private javax.swing.JLabel rsLabel;
    private javax.swing.JTextField rsText;
    private javax.swing.JPanel senderPanel;
    private javax.swing.JLabel unpLabel;
    private javax.swing.JTextField unpText;
    private javax.swing.JLabel vedLabel;
    private javax.swing.JTextField vedText;
    // End of variables declaration//GEN-END:variables
}
