/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.jdbc.tutorial.form;

/**
 *
 * @author asiro
 */
public class FormSender extends javax.swing.JFrame {

    /**
     * Creates new form FormSender
     */
    public FormSender() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        senderTable = new javax.swing.JTable();
        dataPanel = new javax.swing.JPanel();
        vedLabel = new javax.swing.JLabel();
        vedText = new javax.swing.JTextField();
        nameLabel = new javax.swing.JLabel();
        nameText = new javax.swing.JTextField();
        adresLabel = new javax.swing.JLabel();
        adresText = new javax.swing.JTextField();
        rsLabel = new javax.swing.JLabel();
        rsText = new javax.swing.JTextField();
        bankLabel = new javax.swing.JLabel();
        bankText = new javax.swing.JTextField();
        kodbankLabel = new javax.swing.JLabel();
        kodbankText = new javax.swing.JTextField();
        unpLabel = new javax.swing.JLabel();
        unpText = new javax.swing.JTextField();
        senderPanel = new javax.swing.JPanel();
        addButton = new javax.swing.JButton();
        editButton = new javax.swing.JButton();
        removeButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        senderTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(senderTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 560, 170));

        dataPanel.setBackground(new java.awt.Color(255, 255, 255));
        dataPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        dataPanel.setLayout(new java.awt.GridLayout(7, 2));

        vedLabel.setText("Vedomstvo");
        dataPanel.add(vedLabel);
        dataPanel.add(vedText);

        nameLabel.setText("Name");
        dataPanel.add(nameLabel);
        dataPanel.add(nameText);

        adresLabel.setText("Adres");
        dataPanel.add(adresLabel);
        dataPanel.add(adresText);

        rsLabel.setText("RS");
        dataPanel.add(rsLabel);
        dataPanel.add(rsText);

        bankLabel.setText("Bank");
        dataPanel.add(bankLabel);
        dataPanel.add(bankText);

        kodbankLabel.setText("KodBank");
        dataPanel.add(kodbankLabel);
        dataPanel.add(kodbankText);

        unpLabel.setText("UNP");
        dataPanel.add(unpLabel);
        dataPanel.add(unpText);

        getContentPane().add(dataPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 280, 120));

        senderPanel.setBackground(new java.awt.Color(255, 255, 255));
        senderPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        senderPanel.setLayout(new java.awt.GridLayout(3, 1));

        addButton.setText("Add");
        senderPanel.add(addButton);

        editButton.setText("Edit");
        senderPanel.add(editButton);

        removeButton.setText("Remove");
        senderPanel.add(removeButton);

        getContentPane().add(senderPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, 220, 120));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormSender.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormSender.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormSender.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormSender.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormSender().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JLabel adresLabel;
    private javax.swing.JTextField adresText;
    private javax.swing.JLabel bankLabel;
    private javax.swing.JTextField bankText;
    private javax.swing.JPanel dataPanel;
    private javax.swing.JButton editButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel kodbankLabel;
    private javax.swing.JTextField kodbankText;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameText;
    private javax.swing.JButton removeButton;
    private javax.swing.JLabel rsLabel;
    private javax.swing.JTextField rsText;
    private javax.swing.JPanel senderPanel;
    private javax.swing.JTable senderTable;
    private javax.swing.JLabel unpLabel;
    private javax.swing.JTextField unpText;
    private javax.swing.JLabel vedLabel;
    private javax.swing.JTextField vedText;
    // End of variables declaration//GEN-END:variables
}
